---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Create object 'Test-One'
      panos_address_object:
        provider: '{{ provider }}'
        name: 'Test-One'
        value: '1.1.1.1'
        description: 'Description One'
        tag: ['Prod']