---
- name: test acl
  connection: local
  hosts: all
  gather_facts: false
  tasks:
    - name: testacl-ping
      paloaltonetworks.panos.panos_security_rule:
        ip_address: ""
        password: "Palopassword01"
        username: "admin"
        rule_name: 'testACL'
        source_zone: ['vlan2']
        destination_zone: ['vlan3']
        source_ip: ['']
        destination_ip: ['']
        application: ['any']
