---
- hosts: all
  gather_facts: false
  roles:
    - name: Create object 'Test-One'
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        name: 'Test-One'
        value: '1.1.1.1'
        description: 'Description One'
        tag: ['Prod']
